language: go
go:
  - 1.7
  - 1.8
  - 1.9
  - tip
go_import_path: github.com/CCI-MOC/obmd
matrix:
  allow_failures:
    - go: tip

before_script:
  - go get github.com/golang/lint/golint 
scritps:
  - sh -e ci/golint.sh
